apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quickwit.fullname" . }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
type: Opaque
data:
  postgres.password: {{ required "A valid config.postgres.password is required!" .Values.config.postgres.password | b64enc | quote }}
{{- if .Values.config.s3.secret_key }}
  s3.secret_key: {{ .Values.config.s3.secret_key | b64enc | quote }}
{{- end }}
